name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
        env:
          NODE_ENV: production